ids = [
    "memory-app",
    "open",
    "close",
    "modal",
    "genres-selector",
    "outliers-selector",
    "counter",
    "score",
    "tbl",
    "pie-chart",
    "scatter-plot",
    "bar-chart",
    "filters-memory",
    "add-filter-group",
    "filter-groups-container",
    {"type": "group-memory"},
    {"type": "add-filter"},
    {"type": "group-container"},
    {"type": "delete-group"},
    {"type": "filter-row-memory"},
    {"type": "filter_operator"},
    {"type": "filter-variable-selector"},
    {"type": "filter-negate"},
    {"type": "filter-type"},
    {"type": "f-vars-container"},
    {"type": "delete-filter"}]